# Generated by Django 4.2.1 on 2023-05-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNum', models.CharField(max_length=11)),
                ('tripId', models.IntegerField()),
                ('trainNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripId', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('trainNum', models.IntegerField()),
                ('departureTime', models.CharField(max_length=100)),
                ('arrivalTime', models.CharField(max_length=100)),
                ('travelDuration', models.CharField(max_length=100)),
                ('ticketPrice', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
